docs/Files.mdx
docs/FlowRuns.mdx

Update files and flow run images and description where applicable

---

docs/AdminControls.md
docs/DataExplorer.mdx
docs/Files.mdx
docs/FlowEditor.mdx
docs/FlowRuns.mdx
docs/Home.mdx
docs/Notifications.mdx
docs/Quickstart.mdx

Update images for new webapp shell

---

docs/Welcome.md

Added browser limitation comment to bottom of Welcome page, as shown in image below.

Add browser limitation comment to bottom of Welcome screen

---

docs/releases/ReleaseNotes.md

adding release notes from 3.24

update release notes

---

docs/releases/ReleaseNotes.md

Added notes for minor improvements and fixes in operators

Add release notes for 20230330

---

docs/releases/ReleaseNotes.md

Added release notes for Apr 13

Add release notes for Apr 13

---

docs/releases/202304.md

Updated release date to April 21. Added release notes.

Add release notes for Apr 21 2023

---

README.md
docs/Quickstart.mdx

Update to quickstart to smooth learning process and reflect key changes in UX.

Luke quickstart update

---

docs/releases/202306.md
sidebars.js

Add June 1 release notes and June page

Add June 1 release notes

---

docs/releases/202306.md

Added release notes for the June 8 2023 release

Add June 8 release notes

---

docs/releases/202306.md

Added release notes for June 15

Add release notes June 15

---

docs/releases/202306.md

Add release notes for June 23 release

Add June 23 release notes

---

docs/connectivity/Agent.mdx

put in Josh's instructions for Linux install

add linux install instructions for agent

---

docs/Files.mdx

- Rewrite page and add updated images

Update documentation for new files table

---

docs/releases/202307.mdx

Add July 13 release notes

---

docs/Files.mdx
src/css/custom.css

- Update screenshots
- Add newly-supported filterable fields
- Add section about refreshing data

Update Files docs

---

docs/QuickstartBuildFlow.mdx
sidebars.js

@mattcoganymede - saw that you were going to be moving later in the week so figured I'd go ahead and run through the quickstart changes since I had some time today; can you take a look and see if anything needs tweaking

Update quickstart nodes

---

docs/releases/202308.mdx
sidebars.js

Add August 4 release notes

---

docs/releases/202308.mdx

Added August 10 release notes

---

docs/releases/202308.mdx

Add August 17 release notes

---

docs/releases/202308.mdx

Add August 24 release notes

---

docs/releases/202309.mdx
sidebars.js

Add Sept 7 release notes

---

docs/releases/202309.mdx

Add Sept 14 release notes

---

docs/releases/202309.mdx

Sept 21 release notes

---

docs/releases/202310.mdx

Oct 20 release notes

---

docs/releases/202311.mdx

Add Nov 9 release notes

---

docs/AdminControls.mdx
docs/Concepts.mdx
docs/NodeEditor.mdx
docs/QuickstartBuildFlow.mdx
docs/QuickstartCreateDashboard.mdx

some fixes based on jeff's day 1 feedback doc

updates based on jeff's og feedback document

---

docs/connectivity/Agent.mdx

Just wanted to put this in the docs somewhere

add input_bucket arg doc

---

docs/releases/202311.mdx

Add Nov 16 release notes

---

docs/releases/202311.mdx

Added Nov 22 release notes

---

docs/releases/202311.mdx

Add Nov 30 release notes

---

docs/releases/202312.mdx
sidebars.js

Add Dec 7 release notes

---

docs/releases/202312.mdx

Add Dec 14 release notes

---

docs/releases/202312.mdx

Add Dec 22 release notes

---

docs/releases/202401.mdx
sidebars.js

Add Jan 12 release notes

---

docs/releases/202401.mdx

Add Jan 19 release notes

---

docs/releases/202401.mdx

Add Jan 25 release notes

---

docs/releases/202402.mdx

Add Feb 15

---

docs/releases/202402.mdx

Add Feb 22

---

docs/releases/202403.mdx
sidebars.js

Add March 7 release notes

---

docs/releases/202403.mdx

Add Mar 14 release note

---

docs/releases/202403.mdx

Add Mar 21

---

docs/releases/202403.mdx

Add March 28

---

docs/releases/202404.mdx
sidebars.js

Apr 5 release notes

---

docs/releases/202404.mdx

Add Apr 11 release notes

---

docs/releases/202404.mdx

Add Apr 18

---

docs/releases/202404.mdx

Add April 25

---

docs/connectivity/Tags.mdx

_Only add necessary sections. Be concise. Lengthy descriptions should be added to the appropriate doc. Deelte italic sections_
---  
Api of tagging changed so old code would not work. Also need more info about how virtualization stores session and file info

cleanup changed tag api, add note about virtualization

---

docs/releases/202405.mdx
sidebars.js

Add May 2 release notes

---

docs/QuickstartBuildAgent.mdx
docs/Virtualization.mdx
sidebars.js

---  
Add virtualization to documentation

add virtualization

---

docs/Files.mdx
pydoc/requirements.txt

Add a note to the file browser page on advanced search

add advanced search

---

docs/api/AI.mdx
qiacuity_dpcr_example01.csv
sidebars.js

document and give an example for code generation

add codegen

---

docs/Concepts.mdx
docs/connectivity/Agent.mdx

---  
Define Connection vs. Agent

clarify Connection

---

docs/FlowEditor.mdx

Additional Flow Documentation for 
- where to edit it
- where it will show up in the UI

Additional Flow Documentation

---

docs/FlowEditor.mdx
docs/FlowRuns.mdx

Flow Version docs

---

README.md
docs/api/DataValidation.mdx
docs/connectivity/Agent.mdx
docs/connectivity/DebuggingAgents.mdx
docusaurus.config.js

---
Add some additional notes for Linux agents

Cleanup linux agent instructions

---

docs/QuickstartBuildFlow.mdx
docusaurus.config.js
sidebars.js
src/css/custom.css

greater contrast; smaller font size for sidebar

Style sidebar20240812

---

docs/app/intro/Welcome.mdx

add blurbs to offer a little more explanation for some items on the Welcome page

nit20240821

---

docs/app/agents/QuickstartBuildAgent.mdx
docs/app/flows/FlowEditor.mdx
docs/app/flows/QuickstartBuildFlow.mdx
docs/releases/AgentVersionHistory.md

---
Clean up old screenshots for flow and agent quickstarts

quickstart guide cleanup; agent v4.9 notes

---

docs/app/agents/QuickstartBuildAgent.mdx
docs/app/visualization/QuickstartCreateDashboard.mdx

---
Updates labeling of subsections to be consistent across QuickStarts. Adds small text snippets to make page navigation more explicit and updates an outdated agent download image.

20240825-update-minor-quickstart-updates

---

.wordlist.txt
docs/app/agents/Agent.mdx
docs/sdk/markdowns/AgentModelsAndMethods.mdx

---
Add some example user-defined code templates for file watcher agents

add example udc for watch for files locally and run flow agents

---

.wordlist.txt
docs/app/agents/Agent.mdx
docs/app/agents/AgentMonitoring.mdx
docs/sdk/markdowns/AgentModelsAndMethods.mdx

Reason
---
Give a better starting point for development
Notes
---
Also added comment on configuring the output_path variable for cloud watcher agents

Add cloud watcher example

---

.wordlist.txt
docs/app/agents/Agent.mdx
docs/sdk/markdowns/AgentModelsAndMethods.mdx

add cron agent example

---

docs/app/agents/DebuggingAgents.mdx
docs/sdk/markdowns/AgentModelsAndMethods.mdx

- Added installer build issue to troubleshooting guide

nit20240903

---

docs/releases/202410.mdx

Release notes for 17 Oct 2024 release

---

.wordlist.txt
docs/app/configuration/AuditLog.mdx
sidebars.js

AuditLog docs

---

.wordlist.txt
docs/app/agents/BulkUploadInstruments.mdx
docs/app/agents/Instruments.mdx
docs/app/agents/NewInstrument.mdx
sidebars.js

---
Add Instruments documentation

Add Instruments documentation

---

docs/app/admin/ExternalPlatform.mdx

Description
---
Update how users would create AWS role for Ganymede access

update connecting to S3

---

docs/app/agents/DebuggingAgents.mdx
docs/app/flows/NodeEditor.mdx

---
- update agent script
- find save+commit

Update agent script; update save and commit

---

docs/releases/202501.mdx
docs/releases/AgentVersionHistory.md

update agent version history page

---

.wordlist.txt
docs/app/admin/AdminControls.mdx
docs/app/visualization/AnalysisNotebook.mdx
docs/releases/202310.mdx
docs/releases/202405.mdx
docs/releases/202407.mdx
docs/releases/202502.mdx
docs/sdk/Benchling.mdx
docs/sdk/FlowRunAutomation.mdx
docs/sdk/GanymedeClass.mdx
docs/sdk/SendingAlerts.mdx
docs/sdk/markdowns/AgentSDK.mdx
sidebars.js

- make alerting from SDK its own page
- add info on running Flows from SDK, run monitoring with SDK
- change Environment Administration to Environment Settings to align with app; broad set of features in section
- deemphasize Benchling integration

updates 20250206

---

docs/app/agents/Agent.mdx

fix wrong arg

---

docs/app/agents/Agent.mdx

Fix runtime update typo

---

docs/app/visualization/Dashboards.mdx

Added an example for using jinja templating for metric choosing.

Add jinja example

---

docs/app/agents/AgentInstall.mdx
sidebars.js

Description
---
- Update for using script to install linux agent

Update linux install instructions

---

docs/releases/202505.mdx
docs/releases/202506.mdx
sidebars.js

- Release notes for 29 May 2025
- Release notes for 29 May 2025
- Release notes for 5 Jun 2025

Release notes for 5 June 2025

---

.wordlist.txt
docs/app/agents/DebuggingAgents.mdx

help solve agent not resarting issue

add how to increase registry timeout
